version: "3.8"

services:
  event-ingestor:
    build:
      context: .
      dockerfile: event-ingestor/Dockerfile
    container_name: event-ingestor
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:-database}
      CLICKHOUSE_USERNAME: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      WAIT_TIMEOUT: 15
    volumes:
      - ./proto:/proto
    ports:
      - "${GRPC_PORT:-9101}:9001"
    depends_on:
      - clickhouse
    networks:
      - app-net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse/
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE:-database}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
    networks:
      - app-net

volumes:
  clickhouse:

networks:
  app-net:
    driver: bridge
    name: eSanj