version: "3.8"

services:
  event-ingestor:
    build:
      context: .
      dockerfile: event-ingestor/Dockerfile
    container_name: event-ingestor
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:-database}
      CLICKHOUSE_USERNAME: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      WAIT_TIMEOUT: 15
    volumes:
      - ./proto:/proto
    ports:
      - "${GRPC_PORT:-9101}:9001"
    depends_on:
      - clickhouse
    networks:
      - app-net

  query-api:
    build:
      context: .
      dockerfile: query-api/Dockerfile
    container_name: query-api
    volumes:
      - ./proto:/proto
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      - app-net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse/
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE:-database}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
    networks:
      - app-net

  frontend:
    image: nginx:alpine
    container_name: dashboard-frontend
    volumes:
      - ./docker/frontend/nginx:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "${APP_PORT:-8080}:80"
    restart: unless-stopped
    networks:
      - app-net

volumes:
  clickhouse:

networks:
  app-net:
    driver: bridge
    name: eSanj