<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto

namespace GPBMetadata;

class Telemetry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE6\x02\x0A\x0Ftelemetry.proto\x12\x09telemetry\"\xC0\x01\x0A\x05Event\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\x12\x12\x0A\x0Aevent_type\x18\x02 \x01(\x09\x12/\x0A\x0Bhappened_at\x18\x03 \x01(\x0B2\x1A.google.protobuf.Timestamp\x120\x0A\x08metadata\x18\x04 \x03(\x0B2\x1E.telemetry.Event.MetadataEntry\x1A/\x0A\x0DMetadataEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"5\x0A\x11EventPushResponse\x12\x0F\x0A\x07success\x18\x01 \x01(\x08\x12\x0F\x0A\x07message\x18\x02 \x01(\x092F\x0A\x0CEventService\x126\x0A\x04push\x12\x10.telemetry.Event\x1A\x1C.telemetry.EventPushResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

