<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto

namespace GPBMetadata;

class Telemetry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC0\x06\x0A\x0Ftelemetry.proto\x12\x09telemetry\"\xC0\x01\x0A\x05Event\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\x12\x12\x0A\x0Aevent_type\x18\x02 \x01(\x09\x12/\x0A\x0Bhappened_at\x18\x03 \x01(\x0B2\x1A.google.protobuf.Timestamp\x120\x0A\x08metadata\x18\x04 \x03(\x0B2\x1E.telemetry.Event.MetadataEntry\x1A/\x0A\x0DMetadataEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"5\x0A\x11EventPushResponse\x12\x0F\x0A\x07success\x18\x01 \x01(\x08\x12\x0F\x0A\x07message\x18\x02 \x01(\x09\"'\x0A\x11DailyStatsRequest\x12\x12\x0A\x0Aevent_type\x18\x01 \x01(\x09\"9\x0A\x12DailyStatsResponse\x12#\x0A\x05stats\x18\x01 \x03(\x0B2\x14.telemetry.DailyStat\"/\x0A\x09DailyStat\x12\x0D\x0A\x05count\x18\x01 \x01(\x09\x12\x13\x0A\x0Bhappened_at\x18\x02 \x01(\x09\"4\x0A\x0FTopUsersRequest\x12\x12\x0A\x0Aevent_type\x18\x01 \x01(\x09\x12\x0D\x0A\x05limit\x18\x02 \x01(\x0D\"6\x0A\x10TopUsersResponse\x12\"\x0A\x05users\x18\x01 \x03(\x0B2\x13.telemetry.UserStat\"0\x0A\x08UserStat\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\x12\x13\x0A\x0Bevent_count\x18\x02 \x01(\x0D2F\x0A\x0CEventService\x126\x0A\x04Push\x12\x10.telemetry.Event\x1A\x1C.telemetry.EventPushResponse2\xA2\x01\x0A\x0AEventQuery\x12L\x0A\x0DGetDailyStats\x12\x1C.telemetry.DailyStatsRequest\x1A\x1D.telemetry.DailyStatsResponse\x12F\x0A\x0BGetTopUsers\x12\x1A.telemetry.TopUsersRequest\x1A\x1B.telemetry.TopUsersResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

