<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto

namespace Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>telemetry.DailyStat</code>
 */
class DailyStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string count = 1;</code>
     */
    protected $count = '';
    /**
     * Generated from protobuf field <code>string happened_at = 2;</code>
     */
    protected $happened_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $count
     *     @type string $happened_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string count = 1;</code>
     * @return string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>string count = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string happened_at = 2;</code>
     * @return string
     */
    public function getHappenedAt()
    {
        return $this->happened_at;
    }

    /**
     * Generated from protobuf field <code>string happened_at = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHappenedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->happened_at = $var;

        return $this;
    }

}

