<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto

namespace Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>telemetry.HourlyStatsResponse</code>
 */
class HourlyStatsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .telemetry.HourlyStat stats = 1;</code>
     */
    private $stats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Telemetry\HourlyStat>|\Google\Protobuf\Internal\RepeatedField $stats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .telemetry.HourlyStat stats = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>repeated .telemetry.HourlyStat stats = 1;</code>
     * @param array<\Telemetry\HourlyStat>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Telemetry\HourlyStat::class);
        $this->stats = $arr;

        return $this;
    }

}

