<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto

namespace Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>telemetry.TopUsersResponse</code>
 */
class TopUsersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>uint32 event_count = 2;</code>
     */
    protected $event_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type int $event_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 event_count = 2;</code>
     * @return int
     */
    public function getEventCount()
    {
        return $this->event_count;
    }

    /**
     * Generated from protobuf field <code>uint32 event_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEventCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->event_count = $var;

        return $this;
    }

}

